// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Z2xtZlmjrhaSJ_jWijXPffAttQ_wVNw',
    appId: '1:740732040592:web:b2ef3589b9634e75792f15',
    messagingSenderId: '740732040592',
    projectId: 'drillz-7606a',
    authDomain: 'drillz-7606a.firebaseapp.com',
    storageBucket: 'drillz-7606a.appspot.com',
    measurementId: 'G-SK3K0D060K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GWYaKz8T7ICFCh99aYGvgZ1idg_V9-Q',
    appId: '1:740732040592:android:d57b213bbe319cd4792f15',
    messagingSenderId: '740732040592',
    projectId: 'drillz-7606a',
    storageBucket: 'drillz-7606a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCah56I0XqYwEev3kvtsFfSh7iypss91eQ',
    appId: '1:740732040592:ios:48a58b45b59340b7792f15',
    messagingSenderId: '740732040592',
    projectId: 'drillz-7606a',
    storageBucket: 'drillz-7606a.appspot.com',
    iosClientId: '740732040592-sduhimavpcpm8r6cm5uqmvnpvasftbd9.apps.googleusercontent.com',
    iosBundleId: 'com.paraxod.drillz',
  );
}
